# Generated by Django 5.0 on 2023-12-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toppings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
