# Generated by Django 5.0 on 2023-12-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_alter_toppings_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
